language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: hmaarrfk
  password:
    secure: l2Tazup2j42QkGwjalOK8R+4b8K9a0USFFfTI0i1ocOHIy2U7rMLzWUhr+nNj3NeEIdck2O9la0hj7i5ksm03RU0XylgYarWnfd4Nvx85mDjB1JTSFxJNfCVUkU5jqyYK6VDQclYe/CaexIZuA0oeG7AWQMIQa5um3rmI0h9Gt4EMk9BKXqcj8kShD9P5Zr3qoFAAbxiem2t8I1UX6LFoy0a5F3IOB3zCxSJhuxaLOrdJVLdKVMfGLoGq2ZXxNTyoE8L+fnggCD/lMMcres1lkqKoi/rQgPi/TgR9/qOqDnfftRFTwzbfViO0sMRcx6z7zBRKsHdHzEAGPJCLjtVXubXyykGus0+tH03cMEBAFjcTNQcdDDi9TX8om3okafNc7HyOD/PZ1Xv16YfbbtjSzIEOEekXwAppmSN5ueejrQcCDXT9T7wkGhtqiHiTnb1usLcrDEss3JUN9hU/13WaqFlMq/XQu+5jqd64BL9CMxzDtcaaWPQIChNW4/gjbg4iSezDc6mTQeFd+E11zJiuyyzOlr7nZpaCAs9liM7/8SgOomo++9fW6Z9QMw6VUxozVjsCyn6aRA858ucDU48IgIAQwLI4Xqm7XJYNTX6umcLzFlSN57ymqNrQPQ4ZiQ8TqeksTKd98yGqvfjCHybwy63A5OybshNvsC6qUZ8ZSU=
  on:
    tags: true
    repo: ramonaoptics/python-teensytoany
    python: 3.6
