language: python

python:
- 3.8
- 3.7
- 3.6

install:
- pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  user: '__token__'
  password:
    secure: lwO8DFg92Ddee6gbbuHlRJ43xzMvJ1+WTeFucQf9ZVEtxlSP5eilYmkk5KipyrLjLBR4CV003zW6SsY0mKLhY9cFGoxgi5wvZPOEQPz5G/M+ZOIfMXTA8O6g8JvwKa4++0NJ2vjuoCsPchvS8YbKB/0qJMpsSGmggn8IjaRIpbN2OPF+mTb7yimSeW+9ASE8bnsfjtPUfjNfU2Ii/zd4juB+KllFFQg8n7j0ci2pXpKjn/3HxFB2YdGuanEKSVb14X2ygLwBLMETgUUEteUJZac2ytSjBUDNmMmvsrtL44fGuA0qkPhg53bRJ9I4uXk70vWMwydOVs94sFSrEwpyilGKY5qQyx0Yqn6fO35OfyhWafTmC73wGNNJ45o1DSeJCPGYXEW9c3+CprxbXvFeuD3mrz9eyEDc69ri3URZkHoXKQPnQvtBu1VpXJWUxlZm2ang8QClhJIVROO6yfcgzLydNc616yu4o5j9vU8aKIkd0Vp6yYQsnRWKkZwMdr3GBTE/+GYMFZivyw28uRGpFABT7b7JiS+WfxdXOk9t4RlmsdXKZYTeQdA6BieIylPuWfPPvTiUVqi7oB5wbeXL0HpowHwxXFXG3qKVpeUs3DnB2FlWDXZ3kOb7rrQPHl1edfWNdzZKTdvpkomINoocQCxBCbBpxLzhgbq5EcZK29Q=
  on:
    tags: true
    python: 3.6
    # Not sure why I need this
    all_branches: true
